Libra/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Libra.Models;
using Libra.Services;

namespace Libra.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IRepository repository;

        public HomeController(ILogger<HomeController> logger,
            IRepository repository)
        {
            _logger = logger;
            this.repository = repository;
        }

        public IActionResult Index()
        {
            var stocks = repository.GetStocks().Count();
            var warehouse = repository.GetWarehouses().Count();
            var inventory = repository.GetInventories().Count();
            var employee = repository.GetEmployees().Count();

            ViewBag.Stocks = stocks;
            ViewBag.WareHouse = warehouse;
            ViewBag.Inventory = inventory;
            ViewBag.Employee = employee;
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Libra/Controllers/InventoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Libra.Library.Models;
using Libra.Services;
using Libra.ViewModel;

namespace Libra.Controllers
{
    public class InventoriesController : Controller
    {
        private readonly AppConnect _context;

        public InventoriesController(AppConnect context)
        {
            _context = context;
        }

        // GET: Inventories
        public async Task<IActionResult> Index()
        {
            var appConnect = _context.Inventories.Include(i => i.Employee).Include(i => i.Stock).Include(i => i.Warehouse).Select( b => new InventoryViewModel 
            { 
            Id = b.Id,
            DateRecieved = b.DateRecieved,
            Employee = b.Employee.Name,
            StockName = b.Stock.StockName,
            Location = b.Warehouse.Location,
            Unit = b.Units
            
            });
            return View(await appConnect.ToListAsync());
        }

        // GET: Inventories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inventory = await _context.Inventories
                .Include(i => i.Employee)
                .Include(i => i.Stock)
                .Include(i => i.Warehouse)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (inventory == null)
            {
                return NotFound();
            }

            return View(inventory);
        }

        // GET: Inventories/Create
        public IActionResult Create()
        {
            ViewData["Employee"] = new SelectList(_context.Employees, "Name", "Name");
            ViewData["StockName"] = new SelectList(_context.Stocks, "StockName", "StockName");
            ViewData["Location"] = new SelectList(_context.Warehouses, "Location", "Location");
            return View();
        }

        // POST: Inventories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(InventoryViewModel inventoryView)
        {
            if (ModelState.IsValid)
            {
                var EmployeeId = _context.Employees.Where(e => e.Name == inventoryView.Employee).Select(e => e.EmployeeId).FirstOrDefault();
                var StockId = _context.Stocks.Where(s => s.StockName == inventoryView.StockName).Select(s => s.Id).FirstOrDefault();
                var WarehouseId = _context.Warehouses.Where(w => w.Location == inventoryView.Location).Select(w => w.Id).FirstOrDefault();

                Inventory addinventory = new Inventory()
                {
                    DateRecieved = inventoryView.DateRecieved,
                    EmployeeId = EmployeeId,
                    StockId = StockId,
                    Units = inventoryView.Unit,
                    WarehouseId = WarehouseId
                    
                };
                _context.Add(addinventory);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["Employee"] = new SelectList(_context.Employees, "Name", "Name", inventoryView.Employee);
            ViewData["StockName"] = new SelectList(_context.Stocks, "StockName", "StockName", inventoryView.StockName);
            ViewData["Location"] = new SelectList(_context.Warehouses, "Location", "Location", inventoryView.Location);

            return View(inventoryView);
        }



        // GET: Inventories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inventory = await _context.Inventories.FindAsync(id);
            if (inventory == null)
            {
                return NotFound();
            }
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "EmployeeId", "EmployeeId", inventory.EmployeeId);
            ViewData["StockId"] = new SelectList(_context.Stocks, "Id", "Id", inventory.StockId);
            ViewData["WarehouseId"] = new SelectList(_context.Warehouses, "Id", "Id", inventory.WarehouseId);
            return View(inventory);
        }

        // POST: Inventories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DateRecieved,StockId,WarehouseId,EmployeeId")] Inventory inventory)
        {
            if (id != inventory.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(inventory);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InventoryExists(inventory.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "EmployeeId", "EmployeeId", inventory.EmployeeId);
            ViewData["StockId"] = new SelectList(_context.Stocks, "Id", "Id", inventory.StockId);
            ViewData["WarehouseId"] = new SelectList(_context.Warehouses, "Id", "Id", inventory.WarehouseId);
            return View(inventory);
        }

        // GET: Inventories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inventory = await _context.Inventories
                .Include(i => i.Employee)
                .Include(i => i.Stock)
                .Include(i => i.Warehouse)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (inventory == null)
            {
                return NotFound();
            }

            return View(inventory);
        }

        // POST: Inventories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var inventory = await _context.Inventories.FindAsync(id);
            _context.Inventories.Remove(inventory);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InventoryExists(int id)
        {
            return _context.Inventories.Any(e => e.Id == id);
        }
    }
}

Libra/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Libra Stock Manager </h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>


<div class="row">
    <div class="col-sm-3">
        <div class="card text-center">
            <div class="card-body">
                <h5 class="card-title">Inventory Count</h5>
                <h1 class="card-text text-danger font-weight-bolder mb-2">@ViewBag.Inventory</h1>
                <a class="btn btn-primary btn-sm" asp-area="" asp-controller="Inventories" asp-action="Index">View</a> <a class="btn btn-success btn-sm" asp-area="" asp-controller="Inventories" asp-action="Create">Add</a>
                <p class="card-text mt-2"><small class="text-muted">Last updated 3 mins ago</small></p>
            </div>
        </div>
    </div>
    <div class="col-sm-3">
        <div class="card text-center">
            <div class="card-body">
                <h5 class="card-title">Locations</h5>
                <h1 class="card-text text-danger font-weight-bolder mb-2">@ViewBag.Warehouse</h1>
                <a class="btn btn-primary btn-sm" asp-area="" asp-controller="warehouses" asp-action="Index">View</a> <a class="btn btn-success btn-sm" asp-area="" asp-controller="warehouses" asp-action="Create">Add</a>
                <p class="card-text mt-2"><small class="text-muted">Last updated 3 mins ago</small></p>
            </div>
        </div>
    </div>
    <div class="col-sm-3">
        <div class="card text-center">
            <div class="card-body">
                <h5 class="card-title">Employees</h5>
                <h1 class="card-text text-danger font-weight-bolder mb-2">@ViewBag.Employee</h1>
                <a class="btn btn-primary btn-sm" asp-area="" asp-controller="employees" asp-action="Index">View</a> <a class="btn btn-success btn-sm" asp-area="" asp-controller="employees" asp-action="Create">Add</a>
                <p class="card-text mt-2"><small class="text-muted">Last updated 3 mins ago</small></p>
            </div>
        </div>
    </div>
    <div class="col-sm-3">
        <div class="card text-center">
            <div class="card-body">
                <h5 class="card-title">Stocks</h5>
                <h1 class="card-text text-danger font-weight-bolder mb-2">@ViewBag.Stocks</h1>
                <a class="btn btn-primary btn-sm" asp-area="" asp-controller="stocks" asp-action="Index">View</a> <a class="btn btn-success btn-sm" asp-area="" asp-controller="stocks" asp-action="Create">Add</a>
                <p class="card-text mt-2"><small class="text-muted">Last updated 3 mins ago</small></p>
            </div>
        </div>
    </div>
</div>